# Database Credentials
db_host : localhost
db_user : root
db_pass : root
db_name : emailparser

# Email details API URL
email_api_url : http://localhost/sample_api.php

# Document upload API URL
document_upload_url: http://localhost/sample_api_2.php

# Used ID to be used
user_id : me

# Date (yyyy/mm/dd) from which emails should be parsed
start_date : 2018/10/16

# Label under which relevant emails are nested
label_id : Label_6864009176545904706

# Gmail API Constants
OOB_URI : urn:ietf:wg:oauth:2.0:oob
APPLICATION_NAME : Gmail API Ruby Quickstart
CREDENTIALS_PATH : credentials.json
TOKEN_PATH : token.yaml